name: earthcube
channels:
  - conda-forge
  - defaults
dependencies:
  - blas
  - boost-cpp
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cfitsio
  - cryptography
  - curl
  - expat
  - fontconfig
  - freetype
  - freexl
  - gdal
  - geos
  - geotiff
  - gettext
  - giflib
  - hdf4
  - hdf5
  - icu
  - idna
  - intel-openmp
  - jpeg
  - json-c
  - kealib
  - krb5
  - lcms2
  - libcurl
  - libcxx
  - libdap4
  - libedit
  - libev
  - libffi
  - libgdal
  - libgfortran
  - libgfortran5
  - libglib
  - libiconv
  - libkml
  - libnetcdf
  - libnghttp2
  - libpng
  - libpq
  - librttopo
  - libspatialite
  - libssh2
  - libtiff
  - libwebp-base
  - libxml2
  - libzip
  - llvm-openmp
  - lz4-c
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - numpy==1.20.1
  - numpy-base
  - olefile
  - openjpeg
  - openssl
  - pandas
  - pcre
  - pillow
  - pip
  - pixman
  - poppler
  - poppler-data
  - postgresql
  - proj
  - pycparser
  - pyopenssl
  - pysocks
  - python==3.9.4
  - python-dateutil
  - python_abi
  - pytz
  - readline
  - setuptools
  - six
  - sqlite
  - tiledb
  - tk
  - tzcode
  - tzdata
  - urllib3
  - wheel
  - xerces-c
  - xz
  - zlib
  - zstd